import Head from "next/head";
import { useState } from "react";
import { excelParser } from "@/utils/excelParser";
import { map } from "lodash";
import { encrypt } from "@/utils/crypto";
import { sendChat } from "@/utils/teams";

export default function Home() {
  const [items, setItems] = useState([]);
  const [encryptedArray, setEncryptedArray] = useState([]);

  const changeHandler = async (e: any) => {
    const file = e?.target?.files[0];
    const parsedData: any = await excelParser(file);
    console.log(parsedData);
    setItems(parsedData);
  };

  // const onClick = async () => {
  //   map(items, (e) => {
  //     const temp: any = encrypt(e);
  //     setEncryptedArray(temp);
  //   });
  // };
  const onClick = async () => {
    sendChat();
  };
  console.log(encryptedArray);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <input type="file" onChange={changeHandler} />
        </div>
        <button onClick={onClick}>Send</button>
      </main>
    </>
  );
}
